openapi: 3.0.1
info:
  title: Report API
  description: Drug safety reports API
  version: "1.0"
servers:
  - url: /api/v1
paths:
  /reports:
    post:
      summary: Create a new report
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewReportRequest"
      responses:
        "201":
          description: Report created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The ID of the created report
                  message:
                    type: string
                    description: A success message
        "400":
          description: Invalid report request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message indicating the request was invalid
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message indicating a server error
    get:
      summary: Get reports by status
      parameters:
        - name: status
          in: query
          description: The status of the reports to retrieve
          required: true
          schema:
            type: string
            enum:
              - NEW
              - IN_REVIEW
              - CLOSED
      responses:
        "200":
          description: A list of reports
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ReportResponse"
        "400":
          description: Invalid status value
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message indicating the status was invalid
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message indicating a server error
  /reports/{reportId}:
    get:
      summary: Get a report by ID
      parameters:
        - name: reportId
          in: path
          description: The ID of the report to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The requested report
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReportResponse"
        "404":
          description: Report not found
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message indicating a server error
components:
  schemas:
    NewReportRequest:
      type: object
      properties:
        reporterName:
          type: string
          description: The name of the reporter
        productName:
          type: string
          description: The name of the product
        description:
          type: string
          description: The description of the report
        timestamp:
          type: string
          format: date-time
          description: The timestamp of the report
        reportStatus:
          type: string
          description: The status of the report
          enum:
            - NEW
            - IN_REVIEW
            - CLOSED
      required:
        - reporterName
        - productName
        - description
        - timestamp
    ReportResponse:
      type: object
      properties:
        id:
          type: string
          description: The ID of the report
        reporterName:
          type: string
          description: The name of the reporter
        productName:
          type: string
          description: The name of the product
        description:
          type: string
          description: The description of the report
        timestamp:
          type: string
          format: date-time
          description: The timestamp of the report
        status:
          $ref: "#/components/schemas/ReportStatus"
    ReportStatus:
      type: string
      enum:
        - NEW
        - IN_REVIEW
        - CLOSED
      description: The status of the report
